name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false  

    - name: Setup Node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 'stable'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN  }}
        publish_dir: ./build
        publish_branch: pages  
